version: 2.1

jobs:
  number_one:
    docker:
      - image: circleci/ubuntu:latest

    steps:
      - checkout
      - run: ls
      - run: pwd

workflows:
  workflow_test:
    jobs:
      - number_one
